### ISSUE TITLE
Ошибка в проверке на число

### ISSUE THREAD

**Issue by ameyuuno** [kbrodt/offer_search#1]
Функция `is_number` работает некорректно, так как ей пофиг встретится ли вообще цифру и сколько раз она встретит точек и запятых. Также она некорректный вывод даст о пустой строке.

https://github.com/kbrodt/offer_search/blob/2b1f418b23298daaca3448eea5f91f7f8650d4ff/offer_search/slot_filling/yargy_rules.py#L8

**Comment by ameyuuno** [comment]
Я бы исправил простой регуляркой

```python
import re

# regular expression which checks string can be interpreted as positive float in normal
# (usual) form. I just don't give a fuck about exponential form, NaN, etc.
IS_POSITIVE_FLOAT_NF = re.compile(r'^\d+([\.,]\d+)?$')

def is_number(word: str) -> bool:
    return IS_POSITIVE_FLOAT_NF.match(word) is not None
```
 И простит меня наука за мат в комментарии

**Comment by NRshka** [comment]
удалил функционал с дробями, в функцию может попасть только токен
